/- This file is generated by trusted Riemann.fail infrastructure. -/
import ChallengeDeps

noncomputable section

/-- The currently accepted exact lower bound. -/
def currentRecordKappa : ℝ := (6735015 : ℝ) / 10000000

/-- The candidate's exact rational lower bound. -/
def candidateKappa : ℝ := (66812491 : ℝ) / 99194740

end
